import {
  Award,
  BarChart3,
  Bell,
  BookOpen,
  CalendarDays,
  ClipboardCheck,
  ClipboardList,
  FileCheck2,
  DoorOpen,
  GraduationCap,
  HeartPulse,
  ListChecks,
  School,
  Settings,
  ShieldCheck,
  Utensils,
  UserRound,
  Users,
  type LucideIcon,
} from 'lucide-react'

import type { AppSection } from './types'

export const appName = import.meta.env.VITE_APP_NAME || 'MeuEnsino'
export const logoPath = '/MeuEnsino-logo.png'

export const navItems: Array<{ id: AppSection; label: string; description: string; icon: LucideIcon }> = [
  { id: 'dashboard', label: 'Dashboard', description: 'Indicadores pedagogicos', icon: BarChart3 },
  { id: 'schools', label: 'Escolas', description: 'Unidades da rede', icon: School },
  { id: 'classes', label: 'Turmas', description: 'Acompanhamento de turmas', icon: Users },
  { id: 'teachers', label: 'Professores', description: 'Corpo docente', icon: UserRound },
  { id: 'students', label: 'Alunos', description: 'Corpo discente', icon: GraduationCap },
  { id: 'evaluations', label: 'Provas e Simulados', description: 'Provas e simulados', icon: ClipboardCheck },
  { id: 'evaluation-corrections', label: 'Correcao de Provas', description: 'Cartoes resposta e notas', icon: FileCheck2 },
  { id: 'calendar', label: 'Calendario', description: 'Feriados e eventos', icon: CalendarDays },
  { id: 'meals', label: 'Merenda', description: 'Estoque e orcamento', icon: Utensils },
  { id: 'food-requests', label: 'Solicitacoes de Merenda', description: 'Avaliacao nutricional', icon: Utensils },
  { id: 'access', label: 'Cargos', description: 'Permissoes por papel', icon: ShieldCheck },
  { id: 'notifications', label: 'Notificações', description: 'Alertas e comunicados', icon: Bell },
  { id: 'settings', label: 'Perfil', description: 'Conta e preferencias', icon: Settings },
  { id: 'pedagogy', label: 'Acompanhamento Pedagogico', description: 'Alunos em alerta', icon: HeartPulse },
  { id: 'teacher-subjects', label: 'Minhas Materias', description: 'Materias e turmas', icon: BookOpen },
  { id: 'room-reservations', label: 'Reservar Sala', description: 'Ambientes escolares', icon: DoorOpen },
  { id: 'lesson-records', label: 'Registro de Aula', description: 'Conteudo ministrado', icon: ClipboardList },
  { id: 'attendance-list', label: 'Lista de Frequencia', description: 'Chamada por turma', icon: ListChecks },
  { id: 'student-performance', label: 'Frequencia e Desempenho', description: 'Presencas, notas e alertas', icon: BarChart3 },
  { id: 'student-grades', label: 'Minhas Materias', description: 'Materias e notas', icon: Award },
  { id: 'student-attendance', label: 'Minha Frequencia', description: 'Presencas e faltas', icon: ListChecks },
  { id: 'child-attendance', label: 'Frequencia e Desempenho', description: 'Presencas, notas e alertas', icon: ListChecks },
  { id: 'child-performance', label: 'Frequencia e Desempenho', description: 'Presencas, notas e alertas', icon: BarChart3 },
]

export const permissionOptions = [
  'dashboard:ler',
  'escolas:gerenciar',
  'turmas:gerenciar',
  'professores:gerenciar',
  'alunos:gerenciar',
  'responsaveis:gerenciar',
  'simulados:gerenciar',
  'merenda:gerenciar',
  'food.view.own_school',
  'food.request.create',
  'food.request.view.own_school',
  'food.request.edit_when_adjustment',
  'food.request.view.all',
  'food.request.approve',
  'food.request.reject',
  'food.request.request_adjustment',
  'food.stock.view.all',
  'food.expiration_alerts.view',
  'food.view.all',
  'food.request.manage.all',
  'food.stock.manage',
  'food.purchase.manage',
  'food.supplier.manage',
  'food.audit.view',
  'diario:registrar',
  'notas:gerenciar',
  'relatorios:tri',
  'cargos:gerenciar',
  'auditoria:ler',
]
